version: 0.2

env:
  variables:
    SOLUTION: .\WebApplication1.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.6.1

phases:
  build:
    commands:
      - cd APITest
      - '& "C:\ProgramData\chocolatey\bin\NuGet.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'

artifacts:
    files:
        - '**/*'
    discard-paths: yes
    base-directory: 'APITest/WebApplication1/bin*'      
