version: 0.2

env:
    variables:
        S3_BUCKET: "codepipeline-us-east-1-840425570419"
        APP_NAME: "AngularProject"

phases:
    pre_build:
        commands:
        - npm install
        - npm install global @angular/cli@6.0.8

    build:
        commands:
        - echo executing Build Phase
        - npm run build

    post_build:
        commands:
           - aws s3 cp dist s3://${S3_BUCKET}/${APP_NAME} --recursive
        - echo Build completed on `date`

artifacts:
    files:
        - '**/*'
    discard-paths: yes
    base-directory: 'dist*'
