version: 0.2

env:
    variables:
        S3_BUCKET: "codepipeline-us-east-1-840425570419"
        APP_NAME: "AngularProject"

phases:
    pre-build:
        commands:
        - echo executing pre-build Phase
        - npm install
         - npm install global @angular/cli@6.0.8

    build:
        commands:
        - echo executing Build Phase
        - npm run build

post_build:
        commands:
        # Copy dist folder to S3 bucket, As of Angular 6, builds are stored inside an app folder in distribution and not at the root of the dist folder
        - aws s3 cp dist s3://${S3_BUCKET}/${APP_NAME} --recursive

artifacts:
  files:
    - '**/*'
  base-directory:'dist/
