version: 0.2

env:
  variables:
    SOLUTION: .\EBTestApplication.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.7.2

phases:
  build:
    commands:
      - cd API
      - '& "C:\ProgramData\chocolatey\bin\NuGet.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'
artifacts:
  files:
    - .\EBTestApplication\bin\*
