version: 0.2

env:
    variables:
        S3_BUCKET: "codepipeline-us-east-1-840425570419"
        APP_NAME: "AngularProject"
phases:
    pre_build:
        commands:
        - cd Web
        - npm install
        - npm install global @angular/cli@6.0.8

    build:
        commands:
        - npm run build

artifacts:
    files:
        - '**/*'
    discard-paths: yes
    base-directory: 'Web/dist*'
